name: Build Docker Image

on:
  push:
    branches:
      - master

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Copiar repositorio
        uses: actions/checkout@v2

      - name: Login en DockerHub
        uses: docker/login-action@v1
        with:
          username: